/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package edu.cs408.vormund.gui;

import javax.swing.JOptionPane;

import edu.cs408.vormund.DBHelpers;

/**
 *
 * @author isabellee
 */
public class NewBank extends javax.swing.JFrame {

    /**
     * Creates new form NewBank
     */
	
	//DBHelpers DBHelp = new DBHelpers();
	
    public NewBank() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        bankname = new javax.swing.JLabel();
        address = new javax.swing.JLabel();
        accountnum = new javax.swing.JLabel();
        routinglab = new javax.swing.JLabel();
        accounttype = new javax.swing.JLabel();
        namefield = new javax.swing.JTextField();
        addressfield = new javax.swing.JTextField();
        accountfield = new javax.swing.JTextField();
        routingfield = new javax.swing.JTextField();
        acctypefield = new javax.swing.JTextField();
        donebutton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Vormund");

        bankname.setText("Name:");

        address.setText("Address:");

        accountnum.setText("Account #:");

        routinglab.setText("Routing #:");

        accounttype.setText("Account type:");

        donebutton2.setText("Done");
        donebutton2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                donebutton2MouseClicked(evt);
            }
        });

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .add(39, 39, 39)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING)
                    .add(address)
                    .add(bankname)
                    .add(accountnum)
                    .add(routinglab)
                    .add(accounttype))
                .add(18, 18, 18)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING, false)
                    .add(namefield, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 176, Short.MAX_VALUE)
                    .add(addressfield)
                    .add(accountfield)
                    .add(routingfield)
                    .add(acctypefield))
                .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .add(org.jdesktop.layout.GroupLayout.TRAILING, layout.createSequentialGroup()
                .addContainerGap(174, Short.MAX_VALUE)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(org.jdesktop.layout.GroupLayout.TRAILING, layout.createSequentialGroup()
                        .add(jLabel1)
                        .add(169, 169, 169))
                    .add(org.jdesktop.layout.GroupLayout.TRAILING, layout.createSequentialGroup()
                        .add(donebutton2)
                        .add(135, 135, 135))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .add(21, 21, 21)
                .add(jLabel1)
                .add(18, 18, 18)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(bankname)
                    .add(namefield, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(address)
                    .add(addressfield, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .add(18, 18, 18)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING)
                    .add(accountfield, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(accountnum))
                .add(28, 28, 28)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(routingfield, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(routinglab))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING)
                    .add(accounttype)
                    .add(acctypefield, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .add(18, 18, 18)
                .add(donebutton2)
                .addContainerGap(12, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void donebutton2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_donebutton2MouseClicked
        // TODO add your handling code here:

        //Check title
    	UserAccount user_acc = new UserAccount();
    	String bank = namefield.getText().toString();
		String add = addressfield.getText().toString();
		String accnum = accountfield.getText().toString();
		String rou_bal = routingfield.getText().toString();
		String acctype = acctypefield.getText().toString();
		Boolean done = true;
		/*
    	if(bank.length() == 0)
    	{
    		JOptionPane.showMessageDialog(null,"Please fill up the bank name field!");
    		done = false;
    	}
    	else if(add.length() == 0)
    	{
    		JOptionPane.showMessageDialog(null,"Please fill up the address field!");
    		done = false;
    	}
    	else if(accnum.length() == 0)
    	{
    		JOptionPane.showMessageDialog(null,"Please fill up the account # field!");
    		done = false;
    	}
    	else if(rou_bal.length() == 0)
    	{
    		JOptionPane.showMessageDialog(null,"Please fill up the rounting # field!");    
    		done = false;
    	}
    	else if(acctype.length() == 0)
    	{
    		JOptionPane.showMessageDialog(null,"Please fill up the account type field!");
    		done = false;
    	}*/
    
        //Add to database
    	if(user_acc.updating == true)
    	{    			
    		//DBHelp.updateBank(bankid,bank,add,accnum,rou_bal,acctype);
    		user_acc.updating = false;
    	}
    	else
    	{
    		//DBHelp.newBank(bank,add,accnum,rou_bal,acctype);
    		;
    	}
    	
    	if(done == true)
    	{
    		new UserAccount().setVisible(true);
        
    		//dispose
    		dispose();
    	}
    }//GEN-LAST:event_donebutton2MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NewBank.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NewBank.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NewBank.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NewBank.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NewBank().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField accountfield;
    public javax.swing.JLabel accountnum;
    public javax.swing.JLabel accounttype;
    private javax.swing.JTextField acctypefield;
    public javax.swing.JLabel address;
    private javax.swing.JTextField addressfield;
    public javax.swing.JLabel bankname;
    private javax.swing.JButton donebutton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JTextField namefield;
    private javax.swing.JTextField routingfield;
    public javax.swing.JLabel routinglab;
    // End of variables declaration//GEN-END:variables
}
