/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package vormund;

import javax.swing.JFrame;

/**
 *
 * @author mleeli
 */
public class NewUser extends  javax.swing.JFrame {

    /**
     * Creates new form NewUser
     */

    public NewUser() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        title2 = new javax.swing.JLabel();
        newusernamelabel = new javax.swing.JLabel();
        newemaillabel = new javax.swing.JLabel();
        newemaillabel2 = new javax.swing.JLabel();
        newpasswordlabel = new javax.swing.JLabel();
        newpasswordlabel2 = new javax.swing.JLabel();
        newusername = new javax.swing.JTextField();
        newuseremail = new javax.swing.JTextField();
        newuseremail2 = new javax.swing.JTextField();
        done = new javax.swing.JButton();
        passwordfield = new javax.swing.JPasswordField();
        passwordfield2 = new javax.swing.JPasswordField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Vormund");

        title2.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        title2.setText("Vormund");

        newusernamelabel.setText("Username");

        newemaillabel.setText("Email");

        newemaillabel2.setText("Re-type email");

        newpasswordlabel.setText("Password");

        newpasswordlabel2.setText("Re-type password");

        done.setText("Done");
        done.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                doneActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(newpasswordlabel2)
                    .addComponent(newpasswordlabel)
                    .addComponent(newemaillabel2)
                    .addComponent(newemaillabel)
                    .addComponent(newusernamelabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 13, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(title2)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(newuseremail, javax.swing.GroupLayout.DEFAULT_SIZE, 115, Short.MAX_VALUE)
                            .addComponent(newusername)
                            .addComponent(newuseremail2, javax.swing.GroupLayout.DEFAULT_SIZE, 115, Short.MAX_VALUE)
                            .addComponent(passwordfield2)
                            .addComponent(passwordfield))))
                .addGap(127, 127, 127))
            .addGroup(layout.createSequentialGroup()
                .addGap(163, 163, 163)
                .addComponent(done)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(title2)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(newusernamelabel)
                    .addComponent(newusername, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(newemaillabel)
                    .addComponent(newuseremail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(newemaillabel2)
                    .addComponent(newuseremail2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(newpasswordlabel)
                    .addComponent(passwordfield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(newpasswordlabel2)
                    .addComponent(passwordfield2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(done)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>                        

    private void doneActionPerformed(java.awt.event.ActionEvent evt) {                                     
        // TODO add your handling code here:
        dispose();
    }                                    

    // Variables declaration - do not modify                     
    private javax.swing.JButton done;
    private javax.swing.JLabel newemaillabel;
    private javax.swing.JLabel newemaillabel2;
    private javax.swing.JLabel newpasswordlabel;
    private javax.swing.JLabel newpasswordlabel2;
    private javax.swing.JTextField newuseremail;
    private javax.swing.JTextField newuseremail2;
    private javax.swing.JTextField newusername;
    private javax.swing.JLabel newusernamelabel;
    private javax.swing.JPasswordField passwordfield;
    private javax.swing.JPasswordField passwordfield2;
    private javax.swing.JLabel title2;
    // End of variables declaration                   
}
