/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package edu.cs408.vormund.gui;

import java.sql.SQLException;

import javax.swing.JOptionPane;

import edu.cs408.vormund.DBHelpers;

/**
 *
 * @author isabellee
 */
public class SSN extends javax.swing.JFrame {

    /**
     * Creates new form LoginWindow
     */
	private DBHelpers helpers;
    public SSN(DBHelpers h) {
        initComponents();
        helpers = h;
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        title1 = new javax.swing.JLabel();
        name = new javax.swing.JLabel();
        snn = new javax.swing.JLabel();
        namefield = new javax.swing.JTextField();
        ssnfield = new javax.swing.JPasswordField();
        done = new javax.swing.JButton();
        

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        title1.setText("Vormund");

        name.setText("Name");

        snn.setText("SSN");

        done.setText("Done");
        done.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                try {
					doneMouseClicked(evt);
				} catch (SQLException e) {
					// TODO Auto-generated catch block
					e.printStackTrace();
				}
            }
        });

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(layout.createSequentialGroup()
                        .add(172, 172, 172)
                        .add(title1))
                    .add(layout.createSequentialGroup()
                        .add(60, 60, 60)
                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(name)
                            .add(snn))
                        .add(34, 34, 34)
                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING, false)
                            .add(namefield, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 130, Short.MAX_VALUE)
                            .add(ssnfield)))
                    .add(layout.createSequentialGroup()
                        .add(145, 145, 145)
                        .add(done)))
                .addContainerGap(140, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .add(20, 20, 20)
                .add(title1)
                .add(34, 34, 34)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(name)
                    .add(namefield, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .add(20, 20, 20)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(snn)
                    .add(ssnfield, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .add(30, 30, 30)
                .add(done)
                .addContainerGap(95, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void doneMouseClicked(java.awt.event.MouseEvent evt) throws SQLException {//GEN-FIRST:event_doneMouseClicked
        // TODO add your handling code here:

        //Check name and ssn
        //Add to database
    	//UserAccount user_acc = new UserAccount();
    	String user_name = name.getText().toString();
		String social = ssnfield.getText().toString();
		Boolean done = true;
		
    	if(user_name.length() == 0)
    	{
    		JOptionPane.showMessageDialog(null,"Please fill up the name field!");
    		done = false;
    	}
    	else if(social.length() == 0)
    	{
    		JOptionPane.showMessageDialog(null,"Please fill up the SSN field!");
    		done = false;
    		
    	}
    	/*
    	if(!user_acc.updating){
    		int result = helpers.newSocial(user_name, social);
    		if(result == -1)
    		{
    			JOptionPane.showMessageDialog(null,"An entry with the given SSN already exists");
    			return;
    		}
    		
    		user_acc.updating = false;
    		done = true;
    	}
    	else
    	{
    		//Isabel needs to find a way of tracking the id of the data items
    		//helpers.updateSocial(?, user_name, social);
    		done = true;
    	}*/
    	
    	if(done == true)
    	{
    		new UserAccount(helpers).setVisible(true);
        
    		//dispose
    		dispose();
    	}
    }//GEN-LAST:event_doneMouseClicked

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton done;
    public javax.swing.JLabel name;
    private javax.swing.JTextField namefield;
    private javax.swing.JLabel snn;
    public javax.swing.JPasswordField ssnfield;
    private javax.swing.JLabel title1;
    // End of variables declaration//GEN-END:variables
}
